import { useEffect, useMemo, useState } from 'react'
import { ImagePlus, MapPin, ShieldCheck, Sparkles, UploadCloud } from 'lucide-react'
import { motion } from 'motion/react'
import { useDropzone } from 'react-dropzone'
import { useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { useGetAmenitiesQuery } from '../../features/amenities/amenitiesApi'
import {
  useCreatePropertyMutation,
  useDeletePropertyImageMutation,
  useGetPropertyQuery,
  useSetCoverImageMutation,
  useUpdatePropertyMutation,
  useUploadPropertyImagesMutation,
} from '../../features/properties/propertiesApi'
import { LoadingState, PageHeader, Panel, PrimaryButton, SecondaryButton, Select, TextArea, TextInput, pretty } from '../../components/workspace/WorkspaceUI'

const blank = {
  title: '', description: '', propertyType: 'apartment', monthlyRent: '', securityDeposit: '0', negotiable: false,
  availableFrom: new Date().toISOString().slice(0, 10), minimumStayMonths: '1', bedrooms: '1', bathrooms: '1', floor: '',
  totalAreaValue: '', totalAreaUnit: 'sqft', furnishedStatus: 'unfurnished', maxOccupants: '1', area: '', street: '', city: 'Gilgit', landmark: '',
  latitude: '', longitude: '', amenities: [], heatingAvailable: false, hotWaterAvailable: false, electricityBackup: false,
  waterAvailability: 'unknown', roadAccess: 'unknown', winterAccessible: true,
}

const errorMessage = (error) => error?.data?.message || error?.error || 'Something went wrong'

export default function PropertyEditorPage() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [step, setStep] = useState(0); const [form, setForm] = useState(blank)
  const { data: property, isLoading } = useGetPropertyQuery(id, { skip: !editing })
  const { data: amenityData } = useGetAmenitiesQuery()
  const [createProperty, createState] = useCreatePropertyMutation(); const [updateProperty, updateState] = useUpdatePropertyMutation(); const [uploadImages, uploadState] = useUploadPropertyImagesMutation(); const [setCover] = useSetCoverImageMutation(); const [deleteImage] = useDeletePropertyImageMutation()
  const [newFiles, setNewFiles] = useState([])
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ accept: { 'image/jpeg': [], 'image/png': [] }, maxFiles: 8, maxSize: 5 * 1024 * 1024, onDrop: setNewFiles })

  useEffect(() => {
    if (!property) return
    setForm({
      title: property.title || '', description: property.description || '', propertyType: property.propertyType || 'apartment', monthlyRent: String(property.monthlyRent ?? ''), securityDeposit: String(property.securityDeposit ?? 0), negotiable: Boolean(property.negotiable),
      availableFrom: property.availableFrom ? property.availableFrom.slice(0,10) : blank.availableFrom, minimumStayMonths: String(property.minimumStayMonths ?? 1), bedrooms: String(property.bedrooms ?? 0), bathrooms: String(property.bathrooms ?? 0), floor: property.floor == null ? '' : String(property.floor),
      totalAreaValue: property.totalArea?.value == null ? '' : String(property.totalArea.value), totalAreaUnit: property.totalArea?.unit || 'sqft', furnishedStatus: property.furnishedStatus || 'unfurnished', maxOccupants: String(property.maxOccupants ?? 1), area: property.address?.area || '', street: property.address?.street || '', city: property.address?.city || 'Gilgit', landmark: property.address?.landmark || '',
      latitude: property.address?.latitude == null ? '' : String(property.address.latitude), longitude: property.address?.longitude == null ? '' : String(property.address.longitude), amenities: (property.amenities || []).map((a) => a._id || a), heatingAvailable: Boolean(property.livingInfo?.heatingAvailable), hotWaterAvailable: Boolean(property.livingInfo?.hotWaterAvailable), electricityBackup: Boolean(property.livingInfo?.electricityBackup), waterAvailability: property.livingInfo?.waterAvailability || 'unknown', roadAccess: property.livingInfo?.roadAccess || 'unknown', winterAccessible: property.livingInfo?.winterAccessible !== false,
    })
  }, [property])

  const payload = useMemo(() => ({
    title: form.title.trim(), description: form.description.trim(), propertyType: form.propertyType, monthlyRent: Number(form.monthlyRent), securityDeposit: Number(form.securityDeposit || 0), negotiable: form.negotiable,
    availableFrom: form.availableFrom, minimumStayMonths: Number(form.minimumStayMonths), bedrooms: Number(form.bedrooms || 0), bathrooms: Number(form.bathrooms || 0), floor: form.floor === '' ? null : Number(form.floor), totalArea: { value: form.totalAreaValue === '' ? null : Number(form.totalAreaValue), unit: form.totalAreaUnit }, furnishedStatus: form.furnishedStatus, maxOccupants: Number(form.maxOccupants || 1), amenities: form.amenities,
    address: { area: form.area.trim(), street: form.street.trim() || null, city: form.city.trim() || 'Gilgit', landmark: form.landmark.trim() || null, latitude: form.latitude === '' ? null : Number(form.latitude), longitude: form.longitude === '' ? null : Number(form.longitude) },
    livingInfo: { heatingAvailable: form.heatingAvailable, hotWaterAvailable: form.hotWaterAvailable, electricityBackup: form.electricityBackup, waterAvailability: form.waterAvailability, roadAccess: form.roadAccess, winterAccessible: form.winterAccessible },
  }), [form])

  const save = async () => { try { const result = editing ? await updateProperty({ id, ...payload }).unwrap() : await createProperty(payload).unwrap(); const propertyId = editing ? id : result?.data?.property?._id || result?.property?._id; toast.success(editing ? 'Property updated' : 'Property created'); if (!editing && propertyId) navigate(`/owner/properties/${propertyId}/edit`, { replace: true }) } catch (e) { toast.error(errorMessage(e)) } }
  const upload = async () => { if (!newFiles.length || !id) return; try { await uploadImages({ id, files: newFiles }).unwrap(); setNewFiles([]); toast.success('Property images uploaded') } catch (e) { toast.error(errorMessage(e)) } }
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const toggleAmenity = (amenityId) => set('amenities', form.amenities.includes(amenityId) ? form.amenities.filter((id) => id !== amenityId) : [...form.amenities, amenityId])
  if (editing && isLoading) return <LoadingState />

  const steps = ['Basics','Pricing','Details','Location','Amenities','Living score','Images','Review']
  return <><PageHeader eyebrow="Property studio" title={editing ? 'Edit property' : 'Create property'} text="A guided listing workflow keeps every required detail clear before admin review." />
    <div className="mb-6 overflow-x-auto"><div className="flex min-w-max gap-2">{steps.map((label,index) => <button key={label} onClick={() => setStep(index)} className={`rounded-full px-4 py-2 text-xs font-black ${step === index ? 'bg-[#102f26] text-white' : 'bg-white text-slate-500 ring-1 ring-slate-200'}`}>{index + 1}. {label}</button>)}</div></div>
    <Panel><motion.div key={step} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }}>
      {step === 0 && <div className="grid gap-4"><TextInput value={form.title} onChange={(e) => set('title',e.target.value)} placeholder="Property title" /><TextArea value={form.description} onChange={(e) => set('description',e.target.value)} placeholder="Describe the property, surroundings and ideal renter" /><Select value={form.propertyType} onChange={(e) => set('propertyType',e.target.value)}>{['hostel','hostel_bed','shared_room','private_room','apartment','house','upper_portion','lower_portion','studio'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select></div>}
      {step === 1 && <div className="grid gap-4 sm:grid-cols-2"><TextInput type="number" min="0" value={form.monthlyRent} onChange={(e) => set('monthlyRent',e.target.value)} placeholder="Monthly rent" /><TextInput type="number" min="0" value={form.securityDeposit} onChange={(e) => set('securityDeposit',e.target.value)} placeholder="Security deposit" /><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 text-sm font-bold"><input type="checkbox" checked={form.negotiable} onChange={(e) => set('negotiable',e.target.checked)} /> Rent is negotiable</label><TextInput type="date" value={form.availableFrom} onChange={(e) => set('availableFrom',e.target.value)} /></div>}
      {step === 2 && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><TextInput type="number" min="1" value={form.minimumStayMonths} onChange={(e) => set('minimumStayMonths',e.target.value)} placeholder="Minimum stay months" /><TextInput type="number" min="0" value={form.bedrooms} onChange={(e) => set('bedrooms',e.target.value)} placeholder="Bedrooms" /><TextInput type="number" min="0" value={form.bathrooms} onChange={(e) => set('bathrooms',e.target.value)} placeholder="Bathrooms" /><TextInput type="number" value={form.floor} onChange={(e) => set('floor',e.target.value)} placeholder="Floor" /><TextInput type="number" min="0" value={form.totalAreaValue} onChange={(e) => set('totalAreaValue',e.target.value)} placeholder="Total area" /><Select value={form.totalAreaUnit} onChange={(e) => set('totalAreaUnit',e.target.value)}>{['sqft','sqm','kanal','marla'].map((v) => <option key={v} value={v}>{v}</option>)}</Select><Select value={form.furnishedStatus} onChange={(e) => set('furnishedStatus',e.target.value)}>{['furnished','semi_furnished','unfurnished'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select><TextInput type="number" min="1" value={form.maxOccupants} onChange={(e) => set('maxOccupants',e.target.value)} placeholder="Max occupants" /></div>}
      {step === 3 && <div className="grid gap-4 sm:grid-cols-2"><TextInput value={form.area} onChange={(e) => set('area',e.target.value)} placeholder="Area / neighbourhood" /><TextInput value={form.street} onChange={(e) => set('street',e.target.value)} placeholder="Street" /><TextInput value={form.city} onChange={(e) => set('city',e.target.value)} placeholder="City" /><TextInput value={form.landmark} onChange={(e) => set('landmark',e.target.value)} placeholder="Landmark" /><TextInput type="number" step="any" value={form.latitude} onChange={(e) => set('latitude',e.target.value)} placeholder="Latitude" /><TextInput type="number" step="any" value={form.longitude} onChange={(e) => set('longitude',e.target.value)} placeholder="Longitude" /><div className="sm:col-span-2 rounded-2xl bg-[#edf5f1] p-4 text-sm text-[#245545]"><MapPin className="mb-2 h-4 w-4" /> Coordinates are optional now and power the property map experience when supplied.</div></div>}
      {step === 4 && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(amenityData?.amenities || []).map((a) => <button type="button" key={a._id} onClick={() => toggleAmenity(a._id)} className={`rounded-2xl border p-4 text-left text-sm font-black transition ${form.amenities.includes(a._id) ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-white text-slate-600'}`}>{a.name}<p className="mt-1 text-[10px] font-semibold opacity-60">{pretty(a.category)}</p></button>)}</div>}
      {step === 5 && <div><div className="grid gap-3 sm:grid-cols-3">{[['heatingAvailable','Heating'],['hotWaterAvailable','Hot water'],['electricityBackup','Power backup'],['winterAccessible','Winter accessible']].map(([key,label]) => <label key={key} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4 text-sm font-black"><input type="checkbox" checked={form[key]} onChange={(e) => set(key,e.target.checked)} />{label}</label>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select value={form.waterAvailability} onChange={(e) => set('waterAvailability',e.target.value)}>{['excellent','good','limited','unreliable','unknown'].map((v) => <option key={v} value={v}>Water: {pretty(v)}</option>)}</Select><Select value={form.roadAccess} onChange={(e) => set('roadAccess',e.target.value)}>{['excellent','good','limited','difficult','unknown'].map((v) => <option key={v} value={v}>Road: {pretty(v)}</option>)}</Select></div></div>}
      {step === 6 && <div>{!editing ? <div className="rounded-3xl border border-dashed border-slate-300 p-8 text-center"><ImagePlus className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 font-black">Save the basic listing first</p><p className="mt-1 text-sm text-slate-500">Images are attached after the property record exists.</p></div> : <><div {...getRootProps()} className={`cursor-pointer rounded-3xl border-2 border-dashed p-8 text-center ${isDragActive ? 'border-emerald-400 bg-emerald-50' : 'border-slate-300 bg-slate-50'}`}><input {...getInputProps()} /><UploadCloud className="mx-auto h-8 w-8 text-emerald-700" /><p className="mt-3 font-black">Drop JPG/PNG property photos here</p><p className="mt-1 text-xs text-slate-400">Up to 8 files per upload, 5 MB each</p></div>{newFiles.length > 0 && <PrimaryButton disabled={uploadState.isLoading} className="mt-4" onClick={upload}>Upload {newFiles.length} image(s)</PrimaryButton>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(property?.images || []).map((image) => <div key={image.id} className="group relative overflow-hidden rounded-2xl"><img src={image.url} alt={image.alt || property.title} className="aspect-[4/3] w-full object-cover" /><div className="absolute inset-x-2 bottom-2 flex gap-2"><button onClick={() => setCover({ id, imageId: image.id })} className={`rounded-full px-3 py-2 text-[10px] font-black ${image.isCover ? 'bg-emerald-300 text-[#102f26]' : 'bg-white/90 text-slate-800'}`}>{image.isCover ? 'Cover' : 'Set cover'}</button><button onClick={() => deleteImage({ id, imageId: image.id })} className="rounded-full bg-white/90 px-3 py-2 text-[10px] font-black text-rose-600">Delete</button></div></div>)}</div></>}</div>}
      {step === 7 && <div className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Preview</p><h2 className="mt-3 text-2xl font-black">{form.title || 'Untitled property'}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{form.description || 'Add a property description.'}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Rent',form.monthlyRent ? `PKR ${form.monthlyRent}` : '—'],['Type',pretty(form.propertyType)],['Area',form.area || '—'],['Amenities',form.amenities.length]].map(([l,v]) => <div key={l} className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-bold text-slate-400">{l}</p><p className="mt-1 text-sm font-black">{v}</p></div>)}</div></div><div className="rounded-[26px] bg-[#102f26] p-5 text-white"><ShieldCheck className="h-5 w-5 text-emerald-300" /><p className="mt-3 font-black">Before admin review</p><p className="mt-2 text-xs leading-5 text-white/60">Save all details, add at least three images, choose exactly one cover image and select at least one amenity. Then submit from the properties page.</p></div></div>}
    </motion.div><div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-5"><SecondaryButton disabled={step === 0} onClick={() => setStep((v) => Math.max(0,v - 1))}>Back</SecondaryButton><div className="flex gap-2"><PrimaryButton disabled={createState.isLoading || updateState.isLoading} onClick={save}>{editing ? 'Save changes' : 'Create property'}</PrimaryButton>{step < steps.length - 1 && <SecondaryButton onClick={() => setStep((v) => Math.min(steps.length - 1,v + 1))}>Next</SecondaryButton>}</div></div></Panel></>
}
