import { useMemo, useState } from 'react'
import { Bell, Building2, Check, ChevronRight, FileCheck2, Heart, MessageCircle, Plus, Send, ShieldCheck, Sparkles, Star, Trash2, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { useSelector } from 'react-redux'
import {
  useAcceptApplicationMutation,
  useGetMyApplicationsQuery,
  useGetReceivedApplicationsQuery,
  useRejectApplicationMutation,
  useWithdrawApplicationMutation,
} from '../../features/applications/applicationsApi'
import {
  useCancelViewingMutation,
  useCompleteViewingMutation,
  useConfirmViewingMutation,
  useGetMyViewingsQuery,
  useGetReceivedViewingsQuery,
  useRejectViewingMutation,
} from '../../features/viewings/viewingsApi'
import { useCreateTenancyMutation, useEndTenancyMutation, useGetMyTenanciesQuery, useGetOwnedTenanciesQuery } from '../../features/tenancies/tenanciesApi'
import { useGenerateRentScheduleMutation, useGetMyRentRecordsQuery, useGetOwnedRentRecordsQuery, useRecordPaymentMutation } from '../../features/rent/rentApi'
import { useGetConversationsQuery, useGetConversationMessagesQuery, useMarkConversationReadMutation, useSendMessageMutation } from '../../features/messages/messagesApi'
import { useCreateAgreementMutation, useGetAgreementsQuery, useSignAgreementMutation } from '../../features/agreements/agreementsApi'
import { useCreateConditionReportMutation, useGetConditionReportsQuery, useConfirmConditionReportMutation, useUploadConditionEvidenceMutation } from '../../features/conditionReports/conditionReportsApi'
import { useCancelMaintenanceMutation, useCreateMaintenanceMutation, useGetMyMaintenanceQuery, useGetReceivedMaintenanceQuery, useUpdateMaintenanceMutation } from '../../features/maintenance/maintenanceApi'
import { useCreateReviewMutation, useGetMyReviewsQuery, useGetReceivedReviewsQuery } from '../../features/reviews/reviewsApi'
import { useDeleteNotificationMutation, useGetNotificationsQuery, useMarkAllNotificationsReadMutation, useMarkNotificationReadMutation } from '../../features/notifications/notificationsApi'
import { useCreateReportMutation, useGetMyReportsQuery } from '../../features/reports/reportsApi'
import { useGetMyVerificationQuery, useSubmitVerificationMutation } from '../../features/verification/verificationApi'
import { useGetMyPropertiesQuery, useDeletePropertyMutation, useSubmitPropertyMutation } from '../../features/properties/propertiesApi'
import { EmptyState, LoadingState, Modal, PageHeader, Panel, PrimaryButton, SecondaryButton, Select, StatusBadge, TextArea, TextInput, dateTime, money, pretty, shortDate } from '../../components/workspace/WorkspaceUI'

const errorMessage = (error) => error?.data?.message || error?.error || 'Something went wrong'

export function DashboardOverviewPage({ owner = false }) {
  const user = useSelector((state) => state.auth.user)
  const myApps = useGetMyApplicationsQuery(undefined, { skip: owner })
  const receivedApps = useGetReceivedApplicationsQuery(undefined, { skip: !owner })
  const myTenancies = useGetMyTenanciesQuery(undefined, { skip: owner })
  const ownedTenancies = useGetOwnedTenanciesQuery(undefined, { skip: !owner })
  const maintenance = owner ? useGetReceivedMaintenanceQuery() : useGetMyMaintenanceQuery()
  const apps = owner ? receivedApps.data?.applications : myApps.data?.applications
  const tenancies = owner ? ownedTenancies.data?.tenancies : myTenancies.data?.tenancies
  const cards = [
    ['Applications', apps?.length || 0, owner ? '/owner/applications' : '/dashboard/applications', FileCheck2],
    ['Active tenancies', (tenancies || []).filter((item) => item.status === 'active').length, owner ? '/owner/tenancies' : '/dashboard/tenancies', Building2],
    ['Maintenance', maintenance.data?.requests?.length || 0, owner ? '/owner/maintenance' : '/dashboard/maintenance', Wrench],
    [owner ? 'My properties' : 'Saved & matches', owner ? 'Manage' : 'Explore', owner ? '/owner/properties' : '/matches', owner ? Building2 : Sparkles],
  ]
  return <><PageHeader eyebrow={owner ? 'Owner command centre' : 'Rental command centre'} title={`Welcome back, ${user?.name?.split(' ')[0] || 'there'}.`} text={owner ? 'Manage listings, renter requests, tenancy operations and property care from one connected workspace.' : 'Track everything from discovery to applications, tenancy, rent, agreements and property care.'} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, to, Icon]) => <Link key={label} to={to}><Panel className="h-full transition hover:-translate-y-1 hover:shadow-lg"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e8f2ed] text-[#245545]"><Icon className="h-5 w-5" /></div><p className="mt-6 text-3xl font-black tracking-[-.05em]">{value}</p><p className="mt-1 text-sm font-bold text-slate-500">{label}</p></Panel></Link>)}</div>
    <Panel className="mt-6 overflow-hidden bg-[#102f26] text-white"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Rental lifecycle</p><h2 className="mt-3 text-2xl font-black tracking-[-.04em]">Every next step stays connected.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Applications, viewings, agreements, rent records, condition reports, maintenance and reviews all connect back to the same property journey.</p></div><Link to={owner ? '/owner/properties' : '/properties'} className="inline-flex items-center gap-2 rounded-full bg-emerald-300 px-5 py-3 text-sm font-black text-[#102f26]">Continue <ChevronRight className="h-4 w-4" /></Link></div></Panel></>
}

export function ApplicationsPage({ owner = false }) {
  const query = owner ? useGetReceivedApplicationsQuery() : useGetMyApplicationsQuery()
  const [accept, acceptState] = useAcceptApplicationMutation()
  const [reject] = useRejectApplicationMutation()
  const [withdraw] = useWithdrawApplicationMutation()
  const [createTenancy] = useCreateTenancyMutation()
  const act = async (fn, payload, success) => { try { await fn(payload).unwrap(); toast.success(success) } catch (e) { toast.error(errorMessage(e)) } }
  if (query.isLoading) return <LoadingState />
  const items = query.data?.applications || []
  return <><PageHeader eyebrow={owner ? 'Owner inbox' : 'Your applications'} title={owner ? 'Rental applications' : 'Applications'} text={owner ? 'Review renter requests and move accepted applications into tenancy.' : 'Follow the status of every home you have applied for.'} />
    <div className="space-y-4">{items.length ? items.map((item) => <Panel key={item._id}><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge value={item.status} /><span className="text-xs font-bold text-slate-400">{pretty(item.applicationType)}</span></div><h2 className="mt-3 text-lg font-black">{item.property?.title || 'Property'}</h2><p className="mt-1 text-sm text-slate-500">{owner ? `${item.applicant?.name || 'Applicant'} · ${item.applicant?.email || ''}` : `${item.property?.address?.area || ''} · ${money(item.property?.monthlyRent)}/month`}</p>{item.message && <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{item.message}</p>}</div><div className="flex flex-wrap gap-2">{owner && item.status === 'pending' && <><PrimaryButton disabled={acceptState.isLoading} onClick={() => act(accept, item._id, 'Application accepted')}>Accept</PrimaryButton><SecondaryButton onClick={() => act(reject, { id: item._id, reason: 'Application was not selected at this time.' }, 'Application rejected')}>Reject</SecondaryButton></>}{owner && item.status === 'accepted' && <PrimaryButton onClick={() => act(createTenancy, { applicationId: item._id }, 'Tenancy created')}>Create tenancy</PrimaryButton>}{!owner && item.status === 'pending' && <SecondaryButton onClick={() => act(withdraw, item._id, 'Application withdrawn')}>Withdraw</SecondaryButton>}</div></div></Panel>) : <EmptyState title="No applications yet" text={owner ? 'Applications for your published properties will appear here.' : 'Browse rentals and apply when you find the right home.'} />}</div></>
}

export function ViewingsPage({ owner = false }) {
  const query = owner ? useGetReceivedViewingsQuery() : useGetMyViewingsQuery()
  const [confirm] = useConfirmViewingMutation(); const [reject] = useRejectViewingMutation(); const [complete] = useCompleteViewingMutation(); const [cancel] = useCancelViewingMutation()
  const act = async (fn, payload, success) => { try { await fn(payload).unwrap(); toast.success(success) } catch (e) { toast.error(errorMessage(e)) } }
  if (query.isLoading) return <LoadingState />
  const items = query.data?.viewings || []
  return <><PageHeader eyebrow="Visits" title={owner ? 'Viewing requests' : 'Your viewings'} text="Schedule and track in-person property visits without losing the conversation context." />
    <div className="grid gap-4 xl:grid-cols-2">{items.length ? items.map((item) => <Panel key={item._id}><div className="flex items-start justify-between gap-4"><div><StatusBadge value={item.status} /><h2 className="mt-3 font-black">{item.property?.title}</h2><p className="mt-1 text-sm text-slate-500">{dateTime(item.requestedDateTime)}</p>{owner && <p className="mt-2 text-sm font-bold text-slate-700">{item.renter?.name}</p>}</div><FileCheck2 className="h-5 w-5 text-emerald-700" /></div>{item.message && <p className="mt-4 text-sm leading-6 text-slate-600">{item.message}</p>}<div className="mt-5 flex flex-wrap gap-2">{owner && item.status === 'requested' && <><PrimaryButton onClick={() => act(confirm, { id: item._id, ownerResponse: 'Viewing confirmed.' }, 'Viewing confirmed')}>Confirm</PrimaryButton><SecondaryButton onClick={() => act(reject, { id: item._id, ownerResponse: 'Unable to host this viewing time.' }, 'Viewing rejected')}>Reject</SecondaryButton></>}{owner && item.status === 'confirmed' && <PrimaryButton onClick={() => act(complete, item._id, 'Viewing completed')}>Mark completed</PrimaryButton>}{!owner && ['requested','confirmed'].includes(item.status) && <SecondaryButton onClick={() => act(cancel, item._id, 'Viewing cancelled')}>Cancel</SecondaryButton>}</div></Panel>) : <EmptyState title="No viewings yet" />}</div></>
}

export function TenanciesPage({ owner = false }) {
  const query = owner ? useGetOwnedTenanciesQuery() : useGetMyTenanciesQuery()
  const [end] = useEndTenancyMutation(); const [generate] = useGenerateRentScheduleMutation(); const [createAgreement] = useCreateAgreementMutation()
  const act = async (fn, payload, success) => { try { await fn(payload).unwrap(); toast.success(success) } catch (e) { toast.error(errorMessage(e)) } }
  if (query.isLoading) return <LoadingState />
  const items = query.data?.tenancies || []
  return <><PageHeader eyebrow="Rental lifecycle" title={owner ? 'Managed tenancies' : 'My tenancy'} text="The tenancy is the centre of agreements, rent, condition reports, maintenance and post-tenancy reviews." />
    <div className="space-y-4">{items.length ? items.map((item) => <Panel key={item._id}><div className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><div className="flex gap-2"><StatusBadge value={item.status} /><span className="text-xs font-bold text-slate-400">{item.durationMonths} months</span></div><h2 className="mt-3 text-xl font-black">{item.property?.title}</h2><p className="mt-1 text-sm text-slate-500">{item.property?.address?.area} · starts {shortDate(item.startDate)}</p><div className="mt-5 grid max-w-xl grid-cols-2 gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Monthly rent</p><strong className="text-sm">{money(item.agreedMonthlyRent)}</strong></div><div><p className="text-xs text-slate-400">Deposit</p><strong className="text-sm">{money(item.securityDeposit)}</strong></div><div><p className="text-xs text-slate-400">{owner ? 'Renter' : 'Owner'}</p><strong className="text-sm">{owner ? item.renter?.name : item.owner?.name}</strong></div></div></div><div className="flex flex-wrap gap-2 lg:max-w-56 lg:flex-col">{item.status === 'active' && owner && <><PrimaryButton onClick={() => act(generate, item._id, 'Rent schedule created')}>Generate rent ledger</PrimaryButton><SecondaryButton onClick={() => act(createAgreement, { tenancyId: item._id }, 'Agreement created')}>Create agreement</SecondaryButton><SecondaryButton onClick={() => act(end, { id: item._id, reason: 'Tenancy completed' }, 'Tenancy ended')}>End tenancy</SecondaryButton></>}<Link to={`/dashboard/condition-reports?tenancy=${item._id}`} className="inline-flex min-h-11 items-center justify-center rounded-2xl border border-slate-200 px-4 text-sm font-black">Condition reports</Link></div></div></Panel>) : <EmptyState title="No tenancy records yet" />}</div></>
}

export function RentPage({ owner = false }) {
  const query = owner ? useGetOwnedRentRecordsQuery() : useGetMyRentRecordsQuery()
  const [recordPayment] = useRecordPaymentMutation()
  const [payment, setPayment] = useState(null); const [amount, setAmount] = useState(''); const [notes, setNotes] = useState('')
  const submit = async () => { try { await recordPayment({ id: payment._id, amount: Number(amount), notes }).unwrap(); toast.success('Payment recorded'); setPayment(null); setAmount(''); setNotes('') } catch (e) { toast.error(errorMessage(e)) } }
  if (query.isLoading) return <LoadingState />
  const records = query.data?.records || []
  const totals = records.reduce((acc, r) => ({ due: acc.due + Number(r.amountDue || 0), paid: acc.paid + Number(r.amountPaid || 0) }), { due: 0, paid: 0 })
  return <><PageHeader eyebrow="Financial record" title="Rent ledger" text="Manual payment records keep both parties aligned without pretending a payment gateway exists." />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Panel><p className="text-xs font-bold text-slate-400">Total scheduled</p><p className="mt-2 text-2xl font-black">{money(totals.due)}</p></Panel><Panel><p className="text-xs font-bold text-slate-400">Recorded paid</p><p className="mt-2 text-2xl font-black text-emerald-700">{money(totals.paid)}</p></Panel><Panel><p className="text-xs font-bold text-slate-400">Outstanding</p><p className="mt-2 text-2xl font-black text-amber-700">{money(totals.due - totals.paid)}</p></Panel></div>
    <div className="space-y-3">{records.length ? records.map((r) => <Panel key={r._id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><StatusBadge value={r.status} /><span className="text-xs font-bold text-slate-400">{r.period}</span></div><p className="mt-2 font-black">{r.property?.title}</p><p className="mt-1 text-sm text-slate-500">Due {shortDate(r.dueDate)} · {money(r.amountPaid)} / {money(r.amountDue)}</p></div>{owner && r.status !== 'paid' && <PrimaryButton onClick={() => { setPayment(r); setAmount(String(Number(r.amountDue) - Number(r.amountPaid))) }}>Record payment</PrimaryButton>}</div></Panel>) : <EmptyState title="No rent records yet" />}</div>
    <Modal open={Boolean(payment)} onClose={() => setPayment(null)} title="Record rent payment"><div className="space-y-4"><TextInput type="number" min="1" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Payment amount" /><TextArea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Optional payment note" /><PrimaryButton className="w-full" onClick={submit}>Save payment</PrimaryButton></div></Modal></>
}

export function MessagesPage() {
  const { data, isLoading } = useGetConversationsQuery(undefined, { pollingInterval: 15000 })
  const conversations = data?.conversations || []; const [selected, setSelected] = useState(null)
  const active = selected || conversations[0]?._id
  const { data: messageData } = useGetConversationMessagesQuery({ conversationId: active, page: 1, limit: 100 }, { skip: !active, pollingInterval: 8000 })
  const [sendMessage, sendState] = useSendMessageMutation(); const [markRead] = useMarkConversationReadMutation(); const [body, setBody] = useState('')
  const user = useSelector((state) => state.auth.user)
  const submit = async (e) => { e.preventDefault(); if (!body.trim()) return; try { await sendMessage({ conversationId: active, body }).unwrap(); setBody(''); markRead(active) } catch (err) { toast.error(errorMessage(err)) } }
  if (isLoading) return <LoadingState />
  return <><PageHeader eyebrow="Communication" title="Messages" text="Conversations stay attached to a property so the rental context never gets lost." />
    <div className="grid min-h-[620px] overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-sm lg:grid-cols-[330px_1fr]"><aside className="border-b border-slate-200 lg:border-b-0 lg:border-r"><div className="p-4"><p className="text-xs font-black uppercase tracking-[.15em] text-slate-400">Conversations</p></div>{conversations.map((c) => { const other = c.owner?._id === user?.id ? c.renter : c.owner; return <button key={c._id} onClick={() => { setSelected(c._id); markRead(c._id) }} className={`flex w-full gap-3 border-t border-slate-100 p-4 text-left ${active === c._id ? 'bg-[#edf5f1]' : 'hover:bg-slate-50'}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 font-black">{other?.name?.[0] || 'U'}</div><div className="min-w-0"><p className="truncate text-sm font-black">{other?.name || 'Rental conversation'}</p><p className="truncate text-xs text-slate-400">{c.property?.title}</p><p className="mt-1 truncate text-xs text-slate-500">{c.lastMessage?.body || 'Start the conversation'}</p></div>{c.unreadCount > 0 && <span className="ml-auto rounded-full bg-rose-500 px-2 py-1 text-[9px] font-black text-white">{c.unreadCount}</span>}</button> })}</aside><section className="flex min-h-[500px] flex-col"><div className="flex-1 space-y-3 overflow-y-auto bg-[#f8faf9] p-5">{active ? (messageData?.messages || []).map((m) => { const mine = m.sender?._id === user?.id; return <div key={m._id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[75%] rounded-[22px] px-4 py-3 text-sm leading-6 ${mine ? 'bg-[#102f26] text-white' : 'bg-white text-slate-700 shadow-sm ring-1 ring-slate-200'}`}>{m.body}<p className={`mt-1 text-[9px] ${mine ? 'text-white/40' : 'text-slate-400'}`}>{dateTime(m.createdAt)}</p></div></div>}) : <EmptyState title="Choose a conversation" />}</div>{active && <form onSubmit={submit} className="flex gap-2 border-t border-slate-200 p-4"><TextInput value={body} maxLength={2000} onChange={(e) => setBody(e.target.value)} placeholder="Write a message…" /><PrimaryButton disabled={sendState.isLoading} aria-label="Send"><Send className="h-4 w-4" /></PrimaryButton></form>}</section></div></>
}

export function AgreementsPage() {
  const { data, isLoading } = useGetAgreementsQuery(); const [signAgreement] = useSignAgreementMutation(); const [active, setActive] = useState(null); const [legalName, setLegalName] = useState('')
  const submit = async () => { try { await signAgreement({ id: active._id, legalName }).unwrap(); toast.success('Agreement accepted'); setActive(null); setLegalName('') } catch (e) { toast.error(errorMessage(e)) } }
  if (isLoading) return <LoadingState />
  const items = data?.agreements || []
  return <><PageHeader eyebrow="Electronic acceptance" title="Rental agreements" text="Review tenancy terms and explicitly accept them using your legal name. This is electronic acceptance, not a cryptographic digital signature." />
    <div className="space-y-4">{items.length ? items.map((a) => <Panel key={a._id}><div className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><StatusBadge value={a.status} /><h2 className="mt-3 text-lg font-black">{a.property?.title}</h2><p className="mt-1 text-sm text-slate-500">{money(a.monthlyRent)}/month · {a.durationMonths} months · starts {shortDate(a.startDate)}</p><div className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2">{(a.clauses || []).slice(0, 4).map((c, i) => <p key={i} className="rounded-2xl bg-slate-50 p-3"><span className="font-black text-emerald-700">{i + 1}.</span> {c}</p>)}</div></div>{a.status !== 'executed' && <PrimaryButton onClick={() => setActive(a)}>Review & accept</PrimaryButton>}</div></Panel>) : <EmptyState title="No agreements yet" />}</div>
    <Modal open={Boolean(active)} onClose={() => setActive(null)} title="Accept rental agreement"><p className="mb-4 text-sm leading-6 text-slate-500">By continuing you confirm that you reviewed the displayed terms and explicitly accept this rental agreement.</p><TextInput value={legalName} onChange={(e) => setLegalName(e.target.value)} placeholder="Your legal name" /><PrimaryButton className="mt-4 w-full" onClick={submit}>I accept this agreement</PrimaryButton></Modal></>
}

export function ConditionReportsPage() {
  const { data: tenancyData } = useGetMyTenanciesQuery(); const tenancies = tenancyData?.tenancies || []; const [tenancyId, setTenancyId] = useState(''); const selected = tenancyId || tenancies[0]?._id
  const { data, isLoading } = useGetConditionReportsQuery(selected, { skip: !selected }); const [create] = useCreateConditionReportMutation(); const [confirm] = useConfirmConditionReportMutation(); const [upload] = useUploadConditionEvidenceMutation()
  const [type, setType] = useState('move_in'); const [area, setArea] = useState('Living area'); const [condition, setCondition] = useState('good'); const [notes, setNotes] = useState('')
  const submit = async () => { try { await create({ tenancyId: selected, reportType: type, items: [{ area, condition, notes }], overallNotes: notes }).unwrap(); toast.success('Condition report created') } catch (e) { toast.error(errorMessage(e)) } }
  return <><PageHeader eyebrow="Property condition" title="Condition reports" text="Create move-in and move-out records, attach private evidence and confirm the shared record." action={tenancies.length ? <Select value={selected || ''} onChange={(e) => setTenancyId(e.target.value)}>{tenancies.map((t) => <option key={t._id} value={t._id}>{t.property?.title}</option>)}</Select> : null} />
    {!selected ? <EmptyState title="No tenancy available" /> : <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Panel><h2 className="font-black">Create report</h2><div className="mt-4 space-y-3"><Select value={type} onChange={(e) => setType(e.target.value)}><option value="move_in">Move in</option><option value="move_out">Move out</option></Select><TextInput value={area} onChange={(e) => setArea(e.target.value)} placeholder="Area / room" /><Select value={condition} onChange={(e) => setCondition(e.target.value)}>{['excellent','good','fair','poor','damaged'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select><TextArea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Notes" /><PrimaryButton className="w-full" onClick={submit}>Create condition report</PrimaryButton></div></Panel><div className="space-y-4">{isLoading ? <LoadingState /> : (data?.reports || []).map((r) => <Panel key={r._id}><div className="flex items-start justify-between gap-4"><div><StatusBadge value={r.status} /><h3 className="mt-2 font-black">{pretty(r.reportType)} report</h3></div><SecondaryButton onClick={async () => { try { await confirm(r._id).unwrap(); toast.success('Report confirmed') } catch (e) { toast.error(errorMessage(e)) } }}>Confirm</SecondaryButton></div><div className="mt-4 space-y-2">{r.items?.map((item) => <div key={item._id || item.area} className="rounded-2xl bg-slate-50 p-3 text-sm"><strong>{item.area}</strong><span className="ml-2 text-slate-500">{pretty(item.condition)}</span>{item.notes && <p className="mt-1 text-slate-500">{item.notes}</p>}</div>)}</div><label className="mt-4 inline-flex cursor-pointer items-center gap-2 text-xs font-black text-emerald-700">Add evidence<input type="file" accept="image/png,image/jpeg" multiple className="hidden" onChange={async (e) => { const files = [...e.target.files]; if (!files.length) return; try { await upload({ id: r._id, files }).unwrap(); toast.success('Evidence uploaded') } catch (err) { toast.error(errorMessage(err)) } }} /></label></Panel>)}</div></div>}</>
}

export function MaintenancePage({ owner = false }) {
  const query = owner ? useGetReceivedMaintenanceQuery() : useGetMyMaintenanceQuery(); const { data: tenancyData } = useGetMyTenanciesQuery(undefined, { skip: owner }); const [create] = useCreateMaintenanceMutation(); const [update] = useUpdateMaintenanceMutation(); const [cancel] = useCancelMaintenanceMutation(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ tenancyId: '', title: '', description: '', category: 'other', priority: 'medium' })
  const submit = async () => { try { await create(form).unwrap(); toast.success('Maintenance request submitted'); setOpen(false) } catch (e) { toast.error(errorMessage(e)) } }
  if (query.isLoading) return <LoadingState />
  const items = query.data?.requests || []
  return <><PageHeader eyebrow="Property care" title="Maintenance" text={owner ? 'Track renter issues and keep each request moving toward resolution.' : 'Report an issue from an active tenancy and follow the owner response.'} action={!owner ? <PrimaryButton onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> New request</PrimaryButton> : null} />
    <div className="grid gap-4 xl:grid-cols-2">{items.length ? items.map((r) => <Panel key={r._id}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><StatusBadge value={r.status} /><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase text-slate-500">{pretty(r.priority)}</span></div><h2 className="mt-3 font-black">{r.title}</h2><p className="mt-1 text-xs text-slate-400">{r.property?.title} · {pretty(r.category)}</p></div><Wrench className="h-5 w-5 text-emerald-700" /></div><p className="mt-4 text-sm leading-6 text-slate-600">{r.description}</p>{r.ownerResponse && <p className="mt-4 rounded-2xl bg-[#edf5f1] p-3 text-sm text-[#245545]"><strong>Owner:</strong> {r.ownerResponse}</p>}<div className="mt-5 flex gap-2">{owner && r.status !== 'resolved' && <PrimaryButton onClick={async () => { try { await update({ id: r._id, status: r.status === 'pending' ? 'in_progress' : 'resolved', ownerResponse: r.status === 'pending' ? 'We are working on this request.' : 'This issue has been resolved.' }).unwrap(); toast.success('Maintenance updated') } catch (e) { toast.error(errorMessage(e)) } }}>{r.status === 'pending' ? 'Start work' : 'Resolve'}</PrimaryButton>}{!owner && r.status === 'pending' && <SecondaryButton onClick={() => cancel(r._id)}>Cancel</SecondaryButton>}</div></Panel>) : <EmptyState title="No maintenance requests" />}</div>
    <Modal open={open} onClose={() => setOpen(false)} title="New maintenance request"><div className="space-y-3"><Select value={form.tenancyId} onChange={(e) => setForm({ ...form, tenancyId: e.target.value })}><option value="">Choose tenancy</option>{tenancyData?.tenancies?.filter((t) => t.status === 'active').map((t) => <option key={t._id} value={t._id}>{t.property?.title}</option>)}</Select><TextInput value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Issue title" /><TextArea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Describe the problem" /><div className="grid grid-cols-2 gap-3"><Select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{['electricity','water','heating','plumbing','appliance','security','structural','internet','other'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select><Select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{['low','medium','high','urgent'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select></div><PrimaryButton className="w-full" onClick={submit}>Submit request</PrimaryButton></div></Modal></>
}

export function ReviewsPage() {
  const { data: mine } = useGetMyReviewsQuery(); const { data: received } = useGetReceivedReviewsQuery(); const { data: tenancyData } = useGetMyTenanciesQuery(); const [create] = useCreateReviewMutation(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ tenancyId: '', rating: 5, comment: '' })
  const submit = async () => { try { await create(form).unwrap(); toast.success('Review submitted'); setOpen(false) } catch (e) { toast.error(errorMessage(e)) } }
  return <><PageHeader eyebrow="Reputation" title="Reviews" text="Reviews unlock only after a tenancy has ended, keeping feedback tied to a real rental relationship." action={<PrimaryButton onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Write review</PrimaryButton>} />
    <div className="grid gap-6 xl:grid-cols-2"><Panel><h2 className="font-black">Written by you</h2><div className="mt-4 space-y-3">{mine?.reviews?.length ? mine.reviews.map((r) => <div key={r._id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><strong className="text-sm">{r.property?.title}</strong><span className="text-amber-500">{'★'.repeat(r.rating)}</span></div><p className="mt-2 text-sm text-slate-500">{r.comment || 'No written comment'}</p></div>) : <p className="text-sm text-slate-400">No reviews written yet.</p>}</div></Panel><Panel><h2 className="font-black">Received</h2><div className="mt-4 space-y-3">{received?.reviews?.length ? received.reviews.map((r) => <div key={r._id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><strong className="text-sm">{r.reviewer?.name}</strong><span className="text-amber-500">{'★'.repeat(r.rating)}</span></div><p className="mt-2 text-sm text-slate-500">{r.comment || 'No written comment'}</p></div>) : <p className="text-sm text-slate-400">No reviews received yet.</p>}</div></Panel></div>
    <Modal open={open} onClose={() => setOpen(false)} title="Write a review"><div className="space-y-3"><Select value={form.tenancyId} onChange={(e) => setForm({ ...form, tenancyId: e.target.value })}><option value="">Choose ended tenancy</option>{tenancyData?.tenancies?.filter((t) => t.status === 'ended').map((t) => <option key={t._id} value={t._id}>{t.property?.title}</option>)}</Select><Select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })}>{[5,4,3,2,1].map((n) => <option key={n} value={n}>{n} stars</option>)}</Select><TextArea value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} placeholder="Share your experience" /><PrimaryButton className="w-full" onClick={submit}>Submit review</PrimaryButton></div></Modal></>
}

export function NotificationsPage() {
  const { data, isLoading } = useGetNotificationsQuery({ page: 1, limit: 50 }, { pollingInterval: 20000 }); const [read] = useMarkNotificationReadMutation(); const [readAll] = useMarkAllNotificationsReadMutation(); const [remove] = useDeleteNotificationMutation()
  if (isLoading) return <LoadingState />
  const items = data?.notifications || []
  return <><PageHeader eyebrow="Activity centre" title="Notifications" text="Important rental lifecycle updates land here." action={<SecondaryButton onClick={() => readAll()}>Mark all read</SecondaryButton>} /><div className="space-y-3">{items.length ? items.map((n) => <Panel key={n._id} className={!n.isRead ? 'ring-2 ring-emerald-100' : ''}><div className="flex gap-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl ${n.isRead ? 'bg-slate-100 text-slate-500' : 'bg-[#e8f2ed] text-emerald-700'}`}><Bell className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{n.title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{n.message}</p><p className="mt-2 text-[10px] font-bold text-slate-400">{dateTime(n.createdAt)}</p></div><button onClick={() => remove(n._id)} className="text-slate-300 hover:text-rose-500"><Trash2 className="h-4 w-4" /></button></div>{!n.isRead && <button onClick={() => read(n._id)} className="mt-3 text-xs font-black text-emerald-700">Mark read</button>}</div></div></Panel>) : <EmptyState title="You're all caught up" />}</div></>
}

export function ProfilePage() {
  const user = useSelector((state) => state.auth.user); const { data: verification } = useGetMyVerificationQuery()
  return <><PageHeader eyebrow="Account" title="Your profile" text="Your authenticated identity and verification state used across the rental platform." /><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><Panel><div className="flex items-center gap-4">{user?.avatar?.url ? <img src={user.avatar.url} alt="" className="h-20 w-20 rounded-[24px] object-cover" /> : <div className="grid h-20 w-20 place-items-center rounded-[24px] bg-[#e8f2ed] text-2xl font-black text-[#245545]">{user?.name?.[0]}</div>}<div><h2 className="text-xl font-black">{user?.name}</h2><p className="text-sm text-slate-500">{user?.email}</p></div></div><div className="mt-6 flex flex-wrap gap-2"><StatusBadge value={user?.emailVerified ? 'verified' : 'pending'} /><StatusBadge value={user?.accountStatus || 'active'} /></div></Panel><Panel><h2 className="font-black">Account details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['Email',user?.email],['Phone',user?.phone || 'Not provided'],['Role',pretty(user?.role)],['Owner verification',verification?.ownerVerified ? 'Verified owner' : pretty(verification?.verification?.status || 'Not submitted')],['Account created',shortDate(user?.createdAt)],['Phone status',user?.phoneVerified ? 'Verified' : 'Not verified']].map(([l,v]) => <div key={l} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-400">{l}</p><p className="mt-1 text-sm font-black">{v}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-400">Profile editing is not exposed by the current backend API, so this screen intentionally presents verified account data without fake edit controls.</p></Panel></div></>
}

export function ReportsPage() {
  const { data } = useGetMyReportsQuery(); const [create] = useCreateReportMutation(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ targetType: 'property', targetId: '', reason: 'misleading_listing', description: '' })
  const submit = async () => { try { await create(form).unwrap(); toast.success('Report submitted'); setOpen(false) } catch (e) { toast.error(errorMessage(e)) } }
  return <><PageHeader eyebrow="Safety" title="Your reports" text="Report a property or user for review by platform administrators." action={<PrimaryButton onClick={() => setOpen(true)}>New report</PrimaryButton>} /><div className="space-y-3">{data?.reports?.length ? data.reports.map((r) => <Panel key={r._id}><div className="flex items-center justify-between gap-4"><div><StatusBadge value={r.status} /><p className="mt-2 font-black">{pretty(r.reason)}</p><p className="mt-1 text-sm text-slate-500">{r.property?.title || r.reportedUser?.name || pretty(r.targetType)}</p></div><ShieldCheck className="h-5 w-5 text-slate-400" /></div></Panel>) : <EmptyState title="No reports submitted" />}</div><Modal open={open} onClose={() => setOpen(false)} title="Submit a safety report"><div className="space-y-3"><Select value={form.targetType} onChange={(e) => setForm({ ...form, targetType: e.target.value })}><option value="property">Property</option><option value="user">User</option></Select><TextInput value={form.targetId} onChange={(e) => setForm({ ...form, targetId: e.target.value })} placeholder="Target ID" /><Select value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}>{['fraud','misleading_listing','harassment','inappropriate_content','duplicate_listing','safety_concern','other'].map((v) => <option key={v} value={v}>{pretty(v)}</option>)}</Select><TextArea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Describe the issue" /><PrimaryButton className="w-full" onClick={submit}>Submit report</PrimaryButton></div></Modal></>
}

export function OwnerVerificationPage() {
  const { data, isLoading } = useGetMyVerificationQuery(); const [submit, submitState] = useSubmitVerificationMutation(); const [form, setForm] = useState({ cnicLast4: '', cnicFront: null, cnicBack: null, selfie: null })
  if (isLoading) return <LoadingState />
  const current = data?.verification
  const canSubmit = !current || ['rejected','resubmission_required'].includes(current.status)
  const send = async () => { try { await submit(form).unwrap(); toast.success('Verification submitted') } catch (e) { toast.error(errorMessage(e)) } }
  return <><PageHeader eyebrow="Trust & safety" title="Owner verification" text="Identity verification is required before listing a property. Documents are private and reviewed by administrators." /><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><Panel><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e8f2ed] text-emerald-700"><ShieldCheck className="h-6 w-6" /></div><h2 className="mt-5 text-xl font-black">Verification status</h2><div className="mt-3"><StatusBadge value={data?.ownerVerified ? 'verified' : current?.status || 'pending'} /></div>{current?.rejectionReason && <p className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{current.rejectionReason}</p>}{current && <p className="mt-4 text-xs text-slate-400">Attempt #{current.attemptNumber} · submitted {shortDate(current.submittedAt)}</p>}</Panel><Panel><h2 className="font-black">{canSubmit ? 'Submit identity documents' : data?.ownerVerified ? 'Identity verified' : 'Under review'}</h2>{canSubmit ? <div className="mt-5 space-y-4"><TextInput maxLength={4} inputMode="numeric" value={form.cnicLast4} onChange={(e) => setForm({ ...form, cnicLast4: e.target.value.replace(/\D/g,'') })} placeholder="Last 4 CNIC digits" />{[['cnicFront','CNIC front'],['cnicBack','CNIC back'],['selfie','Selfie']].map(([key,label]) => <label key={key} className="block rounded-2xl border border-dashed border-slate-300 p-4 text-sm font-bold text-slate-600">{label}<input type="file" accept="image/png,image/jpeg" className="mt-2 block w-full text-xs" onChange={(e) => setForm({ ...form, [key]: e.target.files?.[0] || null })} /></label>)}<PrimaryButton disabled={submitState.isLoading} className="w-full" onClick={send}>Submit for review</PrimaryButton></div> : <p className="mt-4 text-sm leading-6 text-slate-500">{data?.ownerVerified ? 'You can now create and submit property listings.' : 'Your documents are waiting for an administrator decision.'}</p>}</Panel></div></>
}

export function OwnerPropertiesPage() {
  const { data, isLoading } = useGetMyPropertiesQuery(); const [submit] = useSubmitPropertyMutation(); const [remove] = useDeletePropertyMutation()
  if (isLoading) return <LoadingState />
  const properties = data?.properties || []
  return <><PageHeader eyebrow="Portfolio" title="Your properties" text="Create, edit, upload images and submit listings for admin publication." action={<Link to="/owner/properties/new" className="inline-flex min-h-11 items-center gap-2 rounded-2xl bg-[#102f26] px-4 text-sm font-black text-white"><Plus className="h-4 w-4" /> Add property</Link>} /><div className="grid gap-4 xl:grid-cols-2">{properties.length ? properties.map((p) => <Panel key={p._id}><div className="flex gap-4">{p.images?.[0]?.url ? <img src={p.images.find((i) => i.isCover)?.url || p.images[0].url} alt="" className="h-24 w-28 rounded-2xl object-cover" /> : <div className="grid h-24 w-28 place-items-center rounded-2xl bg-slate-100"><Building2 className="h-5 w-5 text-slate-300" /></div>}<div className="min-w-0 flex-1"><StatusBadge value={p.listingStatus} /><h2 className="mt-2 truncate font-black">{p.title}</h2><p className="mt-1 text-sm text-slate-500">{p.address?.area} · {money(p.monthlyRent)}</p></div></div>{p.rejectionReason && <p className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm text-rose-700">{p.rejectionReason}</p>}<div className="mt-5 flex flex-wrap gap-2"><Link to={`/owner/properties/${p._id}/edit`} className="inline-flex min-h-11 items-center rounded-2xl border border-slate-200 px-4 text-sm font-black">Edit listing</Link>{['draft','rejected'].includes(p.listingStatus) && <PrimaryButton onClick={async () => { try { await submit(p._id).unwrap(); toast.success('Property submitted for review') } catch (e) { toast.error(errorMessage(e)) } }}>Submit for review</PrimaryButton>}{p.listingStatus !== 'rented' && <SecondaryButton onClick={async () => { if (!confirm('Delete this property?')) return; try { await remove(p._id).unwrap(); toast.success('Property deleted') } catch (e) { toast.error(errorMessage(e)) } }}>Delete</SecondaryButton>}</div></Panel>) : <EmptyState title="No properties yet" text="Create your first property after owner verification is approved." />}</div></>
}
